import "./globals.css";
import {
  Poppins,
  DancingScript,
  Montserrat,
  QwitcherGrypen,
} from "next/font/google";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Wild and Free Counseling | Minneapolis Counseling</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/wildandfreelogo.webp" />
      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
